name: Deploy Chat API TEST4
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: SSH And Deploy
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          cp knownhosts ~/.ssh/known_hosts
          ssh  -t -i "keyfile" ubuntu@ec2-54-91-171-12.compute-1.amazonaws.com "sudo bash ~/deploy.sh"